name: Context
on: push

jobs:
  functions:
    runs-on: ubuntu-16.04
    steps:
      - name: dump
        run: |
          echo ${{ contains('hello', '11') }}
          echo ${{ startsWith('hello', 'he') }}
          echo ${{ endsWith('hello', 'lo') }}
          echo ${{ format('Hello {0} {1} {2}', 'World', '!', '!') }}
